# job settings
job_name: default_predict
job_type: PredictJob

# log settings
log_format: json
log_output:
  - console
  - logfile

# file settings
data_dir: data/prediction

# results settings
save_results: False