# job settings
job_name: default_train
job_type: TrainJob

# log settings
log_format: standard

# file settings
data_dir: data/training

# tracking
track: False

# hyps
hyps:
  sel_criterion: r2_score
  models:
    linear_regression: {}
    ridge:
      alpha: [0.8, 1.0]
    lasso:
      alpha: [0.8, 1.0]
      selection: ["cyclic", "random"]
    xgboost:
      learning_rate: [0.5, 0.1]
      max_depth: [3, 5]
      n_estimators: [10, 50]
    random_forest:
      max_depth: [3, 5]
      n_estimators: [10, 50]